KpaTakeHome/Models/ErrorViewModel.cs
using System;

namespace KpaTakeHome.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

KpaTakeHome/Models/ParserDbContext.cs
using Microsoft.EntityFrameworkCore;

namespace KpaTakeHome.Models
{
    public partial class ParserDbContext : DbContext
    {
        public ParserDbContext()
        {
        }

        public ParserDbContext(DbContextOptions<ParserDbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Person> Person { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. See http://go.microsoft.com/fwlink/?LinkId=723263 for guidance on storing connection strings.
                optionsBuilder.UseSqlServer("Server=(localdb)\\mssqllocaldb;Database=KpaDb;Trusted_Connection=True;");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {}
    }
}

KpaTakeHome/Models/Person.cs
using System.Collections.Generic;

namespace KpaTakeHome.Models
{
    public class Person
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }

        private Person() { }

        public Person(IReadOnlyList<string> values) : this(values[0], values[1], values[2]) { }

        private Person(string email, string first, string last)
        {
            Email = email;
            FirstName = first;
            LastName = last;
        }
    }
}

KpaTakeHome/Models/Record.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace KpaTakeHome.Models
{
    public class Record
    {
        public int Id { get; set; }
        public List<string> FieldDataList { get; set; } = new List<string>();
    }
}

KpaTakeHome/Models/RecordSet.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace KpaTakeHome.Models
{
    public class RecordSet
    {
        public int Id { get; set; }
        public List<Person> Persons { get; set; } = new List<Person>();
    }
}

KpaTakeHome/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using KpaTakeHome.Models;

namespace KpaTakeHome.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

KpaTakeHome/Controllers/ParserController.cs
using System.Collections.Generic;
using System.IO;
using System.Linq;
using CsvHelper;
using KpaTakeHome.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace KpaTakeHome.Controllers
{
    public class ParserController : Controller
    {
        public ActionResult Display()
        {
            var db = new ParserDbContext();
            var set = db.Person;
            var people = set.ToList();
            ViewData.Add("People", people);
            return View();
        }

        // GET: Upload
        public ActionResult Upload()
        {
            return View();
        }

        // POST: Upload/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Upload(IFormFile file)
        {
            try {
                var db = new ParserDbContext();
                var stream = Request.Form.Files[0].OpenReadStream();
                var reader = new StreamReader(stream);
                db.Person.AddRange(ReadStream(reader));
                db.SaveChanges();
                return RedirectToAction(nameof(Display));
            } catch {
                return View("Error");
            }
        }

        public static List<Person> ReadStream(StreamReader reader)
        {
            var list = new List<Person>();
            var csv = new CsvReader(reader);
            csv.Configuration.MissingFieldFound = null;
            csv.Read();
            csv.ReadHeader();
            while (csv.Read()) {
                var record = csv.Parser.Context.Record;
                list.Add(new Person(record));
            }
            return list;
        }
    }
}

KpaTakeHome/Controllers/WeatherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace KpaTakeHome.Controllers
{
    public class WeatherController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

KpaTakeHome/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<div class="row">
    <div class="col-md-6">
        <h2>Upload CSV File</h2>
        <ul>
	        <li><a asp-area="" asp-controller="Parser" asp-action="Upload">Upload</a></li>
        </ul>
    </div>
    <div class="col-md-6">
        <h2>Weather</h2>
		<ul>
			<li><a asp-area="" asp-controller="Weather" asp-action="Index">Temperature by Lat./Long.</a></li>
		</ul>
    </div>
</div>

KpaTakeHome/Views/Parser/Display.cshtml
@{
	var people = ViewData["People"] as List<Person> ?? new List<Person>();
	ViewData["Title"] = "Uploaded Data";
}

<h2>Uploaded Data</h2>

<div>
	<table class="table table-striped">
		<thead>
			<tr>
				<th>Email Address</th>
				<th>First Name</th>
				<th>Last Name</th>
			</tr>
		</thead>
		<tbody>
		@foreach (var person in people)
		{
			<tr>
				<td>@person.Email</td>
				<td>@person.FirstName</td>
				<td>@person.LastName</td>
			</tr>
		}
		</tbody>
	</table>
</div>

KpaTakeHome/Views/Parser/Upload.cshtml
@{
	ViewData["Title"] = "Upload CSV File";
}

@using (Html.BeginForm("Upload", "Parser", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
	<h2>Upload CSV File</h2>
	<div class="container" style="text-align: center; padding: 2em;">
		<div class="row">
			<div class="col-lg-12">
				<input id="model" type="file" accept="csv" name="model" data-val="true" data-val-required="File is required" class="btn btn-lg" style="margin: 1em auto;" />
			</div>
		</div>
		<div class="row">
			<div class="col-lg-12 text-center">
				<input class="btn btn-primary" type="submit" value="Upload" />
			</div>
		</div>
	</div>
}

KpaTakeHome/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - KPA Take Home</title>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">KPA Take Home</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
	                <li><a asp-area="" asp-controller="Parser" asp-action="Upload">Upload</a></li>
	                <li><a asp-area="" asp-controller="Weather" asp-action="Index">Temperature</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <partial name="_CookieConsentPartial" />
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - KPA/Benjamin Gray</p>
        </footer>
    </div>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    @RenderSection("Scripts", required: false)
</body>
</html>

KpaTakeHome/Views/Weather/Index.cshtml
@{
	ViewData["Title"] = "Weather - Temperature";
}
<script type="text/javascript">
	function LoadWeather() {
		var div = $('#WeatherResults')[0];
		var lat = $('#Latitude')[0].value;
		var long = $('#Longitude')[0].value;
		var message = Validate(lat, long);
		if (message === 'true') {
			var url = Url(lat, long);
			$.ajax({
				url: url,
				type: 'GET',
				dataType: 'jsonp',
				success: function (data) {
					div.innerHTML = '<p>Temperature: ' + data.currently.temperature + '</p>';
				},
				error: function(data) {
					div.innerHTML = '<p>Error in response: ' + data + '</p>';
				}
			});
		} else {
			div.innerHTML = '<p>' + message + '</p>';
		}
	}

	function Validate(lat, long) {
		if ((lat == '') || (long == '')) {
			return 'Please enter numbers for latitude and longitude.';
		}
		if (isNaN(lat) || isNaN(long)) {
			return 'Please enter only numbers for latitude and longitude.';
		}
		if ((lat < -90) || (lat > 90)) {
			return 'Please enter valid latitude values [-90 to 90].';
		}
		if ((long < -180) || (long > 180)) {
			return 'Please enter valid longitude values [-180 to 180].';
		}
		return 'true';
	}

	function Url(lat, long) {
		var key = '1f9a5eedd4211ec9f965223be81f2020';
		return 'https://api.darksky.net/forecast/' + key + '/' + lat + ',' + long + '';
	}
</script>

<h2>Temperature by Lat./Long.</h2>
<div class="container">
	<div class="row">
		<div class="col-sm-3">
			<label for="Latitude" class="label label-primary" style="font-size: larger;">Latitude:</label>
			<input type="text" id="Latitude" placeholder="-90 to 90 i.e. 40.014257" class="input-lg" />
		</div>
		<div class="col-sm-3">
			<label for="Longitude" class="label label-primary" style="font-size: larger;">Longitude:</label>
			<input type="text" id="Longitude" placeholder="-180 to 180 i.e. -105.126537" class="input-lg" />
		</div>
	</div>
	<div class="row">
		<div class="col-sm-6 text-center" style="padding: 1.5em;">
			<button id="LookupButton" onclick="LoadWeather();" class="btn btn-primary">Find Temperature</button>
		</div>
	</div>
</div>
<div class="container" style="padding: 2em;">
	<div id="WeatherResults" class="col-sm-6 h3 text-primary">
	</div>
</div>